CREATE TABLE IF NOT EXISTS USERS
(
  ID              serial primary key,
  DATE_OF_SIGN_UP timestamp without time zone,
  USER_NAME       varchar(20) unique not null,
  IS_ADMIN        boolean
);

CREATE TABLE IF NOT EXISTS LESSONS_ITEMS
(
  ID        serial primary key,
  NAME      varchar(40) not null,
  "order"   smallint    not null,
  CONTENT   varchar(355),
  TITLE_IMG varchar(60)
);

CREATE TABLE IF NOT EXISTS LESSONS
(
  ID             serial primary key,
  TITLE          varchar(40) not null,
  "order"        smallint    not null,
  LESSON_ITEM_ID bigint,
  CONSTRAINT LESSONS_LESSON_ITEM_ID_FKEY FOREIGN KEY (LESSON_ITEM_ID)
    REFERENCES LESSONS_ITEMS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS MODULES
(
  ID          serial primary key,
  TITLE       varchar(40)  not null,
  DESCRIPTION varchar(355) not null,
  TITLE_IMG   varchar(60),
  "order"     smallint     not null,
  LESSON_ID   bigint,
  CONSTRAINT MODULES_LESSON_ID_FKEY FOREIGN KEY (LESSON_ID)
    REFERENCES LESSONS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS COURSES
(
  ID         serial primary key,
  MODULE_ID  bigint,
  TITLE      VARCHAR(30) not null,
  CREATOR_ID bigint,
  CONSTRAINT COURSES_MODULE_ID_FKEY FOREIGN KEY (MODULE_ID)
    REFERENCES MODULES (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT COURSES_CREATOR_ID_FKEY FOREIGN KEY (CREATOR_ID)
    REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS USERS_LESSON_ITEMS
(
  USER_ID        bigint,
  LESSON_ITEM_ID bigint,
  STATUS         VARCHAR(20),
  primary key (USER_ID, LESSON_ITEM_ID),
  CONSTRAINT USERS_LESSON_ITEMS_USER_ID_FKEY FOREIGN KEY (USER_ID)
    REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT USERS_LESSON_ITEMS_LESSON_ITEM_ID_FKEY FOREIGN KEY (LESSON_ITEM_ID)
    REFERENCES LESSONS_ITEMS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

